# Generated by Django 4.1.5 on 2023-01-30 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_staff',
            new_name='staff',
        ),
    ]
