# Generated by Django 4.1.5 on 2023-01-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_active_usuario_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='active',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='admin',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='staff',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
