# Generated by Django 4.1.5 on 2023-01-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
    ]
