# Generated by Django 4.1.5 on 2023-02-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_usuario_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='email',
        ),
    ]
